/*
 * Copyright (c) 2025 Ryan Moeller
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>

#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>

int luaopen_netinet_tcp(lua_State *);

/* TODO: option struct pack/unpack functions */

int
luaopen_netinet_tcp(lua_State *L)
{
	lua_newtable(L);
#define DEFINE(ident) ({ \
	lua_pushinteger(L, TCP_ ## ident); \
	lua_setfield(L, -2, #ident); \
})
	DEFINE(MSS);
	DEFINE(MINMSS);
	DEFINE(MAXWIN);
	DEFINE(MAX_WINSHIFT);
	DEFINE(MAXHLEN);
	DEFINE(MAXOLEN);
	DEFINE(FASTOPEN_MIN_COOKIE_LEN);
	DEFINE(FASTOPEN_MAX_COOKIE_LEN);
	DEFINE(FASTOPEN_PSK_LEN);

	DEFINE(NODELAY);
	DEFINE(MAXSEG);
	DEFINE(NOPUSH);
	DEFINE(NOOPT);
	DEFINE(MD5SIG);
	DEFINE(INFO);
	DEFINE(STATS);
	DEFINE(LOG);
	DEFINE(LOGBUF);
	DEFINE(LOGID);
	DEFINE(LOGDUMP);
	DEFINE(LOGDUMPID);
	DEFINE(TXTLS_ENABLE);
	DEFINE(TXTLS_MODE);
	DEFINE(RXTLS_ENABLE);
	DEFINE(RXTLS_MODE);
	DEFINE(IWND_NB);
	DEFINE(IWND_NSEG);
	DEFINE(LOGID_CNT);
	DEFINE(LOG_TAG);
	DEFINE(USER_LOG);
	DEFINE(CONGESTION);
	DEFINE(CCALGOOPT);
	DEFINE(MAXUNACKTIME);
#ifdef TCP_MAXPEAKRATE /* removed */
	DEFINE(MAXPEAKRATE);
#endif
	DEFINE(IDLE_REDUCE);
	DEFINE(REMOTE_UDP_ENCAPS_PORT);
	DEFINE(DELACK);
	DEFINE(FIN_IS_RST);
	DEFINE(LOG_LIMIT);
	DEFINE(SHARED_CWND_ALLOWED);
	DEFINE(PROC_ACCOUNTING);
	DEFINE(USE_CMP_ACKS);
	DEFINE(PERF_INFO);
	DEFINE(KEEPINIT);
	DEFINE(KEEPIDLE);
	DEFINE(KEEPINTVL);
	DEFINE(KEEPCNT);
	DEFINE(FASTOPEN);
#ifdef TCP_PCAP_OUT /* removed */
	DEFINE(PCAP_OUT);
#endif
#ifdef TCP_PCAP_IN /* removed */
	DEFINE(PCAP_IN);
#endif
	DEFINE(FUNCTION_BLK);
#ifdef TCP_FUNCTION_ALIAS
	DEFINE(FUNCTION_ALIAS);
#endif
	DEFINE(REUSPORT_LB_NUMA);
	DEFINE(RACK_MBUF_QUEUE);
#ifdef TCP_RACK_PROP /* removed */
	DEFINE(RACK_PROP);
#endif
	DEFINE(RACK_TLP_REDUCE);
#ifdef TCP_RACK_PACE_REDUCE /* removed */
	DEFINE(RACK_PACE_REDUCE);
#endif
	DEFINE(RACK_PACE_MAX_SEG);
	DEFINE(RACK_PACE_ALWAYS);
#ifdef TCP_RACK_PROP_RATE /* removed */
	DEFINE(RACK_PROP_RATE);
#endif
	DEFINE(RACK_PRR_SENDALOT);
	DEFINE(RACK_MIN_TO);
#ifdef TCP_RACK_EARLY_RECOV /* removed */
	DEFINE(RACK_EARLY_RECOV);
#endif
	DEFINE(RACK_EARLY_SEG);
	DEFINE(RACK_REORD_THRESH);
	DEFINE(RACK_REORD_FADE);
	DEFINE(RACK_TLP_THRESH);
	DEFINE(RACK_PKT_DELAY);
#ifdef TCP_RACK_TLP_INC_VAR /* removed */
	DEFINE(RACK_TLP_INC_VAR);
#endif
	DEFINE(BBR_IWINTSO);
#ifdef TCP_BBR_RECFORCE /* removed */
	DEFINE(BBR_RECFORCE);
#endif
	DEFINE(BBR_STARTUP_PG);
	DEFINE(BBR_DRAIN_PG);
#ifdef TCP_BBR_RWND_IS_APP /* removed */
	DEFINE(BBR_RWND_IS_APP);
#endif
	DEFINE(BBR_PROBE_RTT_INT);
#ifdef TCP_BBR_ONE_RETRAN /* removed */
	DEFINE(BBR_ONE_RETRAN);
#endif
	DEFINE(BBR_STARTUP_LOSS_EXIT);
#ifdef TCP_BBR_USE_LOWGAIN /* removed */
	DEFINE(BBR_USE_LOWGAIN);
#endif
#ifdef TCP_BBR_LOWGAIN_THRESH /* replaced */
	DEFINE(BBR_LOWGAIN_THRESH);
#endif
#ifdef TCP_BBR_TSLIMITS /* replaced TCP_BBR_LOWGAIN_THRESH */
	DEFINE(BBR_TSLIMITS);
#endif
	DEFINE(BBR_PACE_OH);
#ifdef TCP_BBR_LOWGAIN_FD /* removed */
	DEFINE(BBR_LOWGAIN_FD);
#endif
	DEFINE(BBR_USEDEL_RATE);
	DEFINE(BBR_MIN_RTO);
	DEFINE(BBR_MAX_RTO);
#ifdef TCP_BBR_REC_OVER_HPTS /* removed */
	DEFINE(BBR_REC_OVER_HPTS);
#endif
	DEFINE(BBR_ALGORITHM);
#ifdef TCP_BBR_DRAIN_INC_EXTRA /* removed */
	DEFINE(BBR_DRAIN_INC_EXTRA);
#endif
#ifdef TCP_BBR_STARTUP_EXIT_EPOCH /* removed */
	DEFINE(BBR_STARTUP_EXIT_EPOCH);
#endif
	DEFINE(BBR_PACE_PER_SEC);
	DEFINE(BBR_PACE_DEL_TAR);
	DEFINE(BBR_PACE_SEG_MAX);
	DEFINE(BBR_PACE_SEG_MIN);
	DEFINE(BBR_PACE_CROSS);
#ifdef TCP_RACK_IDLE_REDUCE_HIGH /* removed */
	DEFINE(RACK_IDLE_REDUCE_HIGH);
#endif
#ifdef TCP_RACK_MIN_PACE /* removed */
	DEFINE(RACK_MIN_PACE);
#endif
#ifdef TCP_RACK_MIN_PACE_SEG /* removed */
	DEFINE(RACK_MIN_PACE_SEG);
#endif
#ifdef TCP_RACK_GP_INCREASE /* removed */
	DEFINE(RACK_GP_INCREASE);
#endif
	DEFINE(BBR_TMR_PACE_OH);
	DEFINE(RACK_DO_DETECTION);
	DEFINE(BBR_RACK_RTT_USE);
	DEFINE(BBR_RETRAN_WTSO);
	DEFINE(DATA_AFTER_CLOSE);
	DEFINE(BBR_PROBE_RTT_GAIN);
	DEFINE(BBR_PROBE_RTT_LEN);
	DEFINE(BBR_SEND_IWND_IN_TSO);
	DEFINE(BBR_USE_RACK_RR);
	DEFINE(BBR_HDWR_PACE);
	DEFINE(BBR_UTTER_MAX_TSO);
	DEFINE(BBR_EXTRA_STATE);
	DEFINE(BBR_FLOOR_MIN_TSO);
	DEFINE(BBR_MIN_TOPACEOUT);
	DEFINE(BBR_TSTMP_RAISES);
	DEFINE(BBR_POLICER_DETECT);
	DEFINE(BBR_RACK_INIT_RATE);
	DEFINE(RACK_RR_CONF);
	DEFINE(RACK_GP_INCREASE_CA);
	DEFINE(RACK_GP_INCREASE_SS);
	DEFINE(RACK_GP_INCREASE_REC);
	DEFINE(RACK_FORCE_MSEG);
	DEFINE(RACK_PACE_RATE_CA);
	DEFINE(RACK_PACE_RATE_SS);
	DEFINE(RACK_PACE_RATE_REC);
	DEFINE(NO_PRR);
	DEFINE(RACK_NONRXT_CFG_RATE);
	DEFINE(SHARED_CWND_ENABLE);
	DEFINE(TIMELY_DYN_ADJ);
	DEFINE(RACK_NO_PUSH_AT_MAX);
	DEFINE(RACK_PACE_TO_FILL);
	DEFINE(SHARED_CWND_TIME_LIMIT);
	DEFINE(RACK_PROFILE);
	DEFINE(HDWR_RATE_CAP);
	DEFINE(PACING_RATE_CAP);
	DEFINE(HDWR_UP_ONLY);
	DEFINE(RACK_ABC_VAL);
	DEFINE(REC_ABC_VAL);
	DEFINE(RACK_MEASURE_CNT);
	DEFINE(DEFER_OPTIONS);
#ifdef TCP_FAST_RSM_HACK /* removed */
	DEFINE(FAST_RSM_HACK);
#endif
	DEFINE(RACK_PACING_BETA);
	DEFINE(RACK_PACING_BETA_ECN);
	DEFINE(RACK_TIMER_SLOP);
#ifdef TCP_RACK_DSACK_OPT
	DEFINE(RACK_DSACK_OPT);
#endif
#ifdef TCP_RACK_ENABLE_HYSTART
	DEFINE(RACK_ENABLE_HYSTART);
#endif
#ifdef TCP_RACK_SET_RXT_OPTIONS
	DEFINE(RACK_SET_RXT_OPTIONS);
#endif
#ifdef TCP_RACK_HI_BETA
	DEFINE(RACK_HI_BETA);
#endif
#ifdef TCP_RACK_SPLIT_LIMIT
	DEFINE(RACK_SPLIT_LIMIT);
#endif
#ifdef TCP_RACK_PACING_DIVISOR
	DEFINE(RACK_PACING_DIVISOR);
#endif
#ifdef TCP_RACK_PACE_MIN_SEG
	DEFINE(RACK_PACE_MIN_SEG);
#endif
#ifdef TCP_HYBRID_PACING
	DEFINE(HYBRID_PACING);
#endif
#ifdef TCP_PACING_DND
	DEFINE(PACING_DND);
#endif
#ifdef TCP_SS_EEXIT
	DEFINE(SS_EEXIT);
#endif
#ifdef TCP_DGP_UPPER_BOUNDS
	DEFINE(DGP_UPPER_BOUNDS);
#endif
#ifdef TCP_NO_TIMELY
	DEFINE(NO_TIMELY);
#endif
#ifdef TCP_HONOR_HPTS_MIN
	DEFINE(HONOR_HPTS_MIN);
#endif
#ifdef TCP_REC_IS_DYN
	DEFINE(REC_IS_DYN);
#endif
#ifdef TCP_SIDECHAN_DIS
	DEFINE(SIDECHAN_DIS);
#endif
#ifdef TCP_FILLCW_RATE_CAP
	DEFINE(FILLCW_RATE_CAP);
#endif
#ifdef TCP_STACK_SPEC_INFO
	DEFINE(STACK_SPEC_INFO);
#endif
#ifdef TCP_GP_USE_LTBW
	DEFINE(GP_USE_LTBW);
#endif

	DEFINE(VENDOR);
	DEFINE(CA_NAME_MAX);
	DEFINE(LOG_ID_LEN);
#ifdef TCP_NUM_PROC_COUNTERS
	DEFINE(NUM_PROC_COUNTERS);
#endif
#ifdef TCP_NUM_CNT_COUNTERS
	DEFINE(NUM_CNT_COUNTERS);
#endif
	DEFINE(FUNCTION_NAME_LEN_MAX);
	DEFINE(TLS_MODE_NONE);
	DEFINE(TLS_MODE_SW);
	DEFINE(TLS_MODE_IFNET);
	DEFINE(TLS_MODE_TOE);
#ifdef TCP_LOG_USER_HTTPD
	DEFINE(LOG_USER_HTTPD);
#endif
#ifdef TCP_LOG_HTTPD_TS
	DEFINE(LOG_HTTPD_TS);
#endif
#ifdef TCP_LOG_HTTPD_TS_REQ
	DEFINE(LOG_HTTPD_TS_REQ);
#endif
#ifdef TCP_LOG_HTTPD_RANGE_START
	DEFINE(LOG_HTTPD_RANGE_START);
#endif
#ifdef TCP_LOG_HTTPD_RANGE_END
	DEFINE(LOG_HTTPD_RANGE_END);
#endif
#ifdef TCP_HYBRID_PACING_CU
	DEFINE(HYBRID_PACING_CU);
#endif
#ifdef TCP_HYBRID_PACING_DTL
	DEFINE(HYBRID_PACING_DTL);
#endif
#ifdef TCP_HYBRID_PACING_CSPR
	DEFINE(HYBRID_PACING_CSPR);
#endif
#ifdef TCP_HYBRID_PACING_H_MS
	DEFINE(HYBRID_PACING_H_MS);
#endif
#ifdef TCP_HYBRID_PACING_ENABLE
	DEFINE(HYBRID_PACING_ENABLE);
#endif
	DEFINE(REUSPORT_LB_NUMA_NODOM);
	DEFINE(REUSPORT_LB_NUMA_CURDOM);
#undef DEFINE
#define DEFINE(ident) ({ \
	lua_pushinteger(L, ident); \
	lua_setfield(L, -2, #ident); \
})
	DEFINE(TCP_MSS); /* full name of MSS defined above */
	DEFINE(TCP6_MSS);
	DEFINE(TTCP_CLIENT_SND_WND);
#ifdef RACK_CSPR_IS_FCC
	DEFINE(RACK_CSPR_IS_FCC);
#endif
	DEFINE(TCPI_OPT_TIMESTAMPS);
	DEFINE(TCPI_OPT_SACK);
	DEFINE(TCPI_OPT_WSCALE);
	DEFINE(TCPI_OPT_ECN);
	DEFINE(TCPI_OPT_TOE);
	DEFINE(TCPI_OPT_TFO);
#ifdef TCPI_OPT_ACE
	DEFINE(TCPI_OPT_ACE);
#endif
	DEFINE(TLS_SET_RECORD_TYPE);
	DEFINE(TLS_GET_RECORD);
	DEFINE(VOI_TCP_TXPB);
	DEFINE(VOI_TCP_RETXPB);
	DEFINE(VOI_TCP_FRWIN);
	DEFINE(VOI_TCP_LCWIN);
	DEFINE(VOI_TCP_RTT);
	DEFINE(VOI_TCP_CSIG);
	DEFINE(VOI_TCP_GPUT);
	DEFINE(VOI_TCP_CALCFRWINDIFF);
	DEFINE(VOI_TCP_GPUT_ND);
	DEFINE(VOI_TCP_ACKLEN);
#undef DEFINE
	return (1);
}
