freebsd_instance:
  cpu: 1
  memory: 1G

task:
  matrix:
    - name: releases/amd64/13.5-RELEASE
      freebsd_instance:
        image_family: freebsd-13-5
    - name: releases/amd64/14.3-RELEASE
      freebsd_instance:
        image_family: freebsd-14-3
    - name: releases/amd64/15.0-RC2
      freebsd_instance:
        image_family: freebsd-15-0-amd64-ufs
  stateful: false
  env:
    ARCHIVES_BASE: https://download.freebsd.org/${CIRRUS_TASK_NAME}
  build_setup_script:
    - test -e /usr/src/contrib/lua/src/lua.h || fetch -o - ${ARCHIVES_BASE}/src.txz | tar x -C /
  build_script:
    - make -j${CIRRUS_CPU}
    - make install
  manlint_script:
    - makewhatis /usr/share/man
    # XXX: too many xrefs to manpages that don't exist in previous releases
    - test $(sysctl -n kern.osreldate) -lt 1500000 || make manlint
  # TODO: tests
