freebsd_instance:
  cpu: 1
  memory: 1G

task:
  matrix:
    - name: releases/amd64/13.5-RELEASE
      freebsd_instance:
        image_family: freebsd-13-5
    - name: releases/amd64/14.3-RELEASE
      freebsd_instance:
        image_family: freebsd-14-3
    - name: snapshots/amd64/15.0-ALPHA4
      freebsd_instance:
        image_family: freebsd-15-0
  stateful: false
  env:
    WD: /tmp/wd
    ARCHIVES_BASE: https://download.freebsd.org/${CIRRUS_TASK_NAME}
  build_setup_script:
    - mkdir ${WD}
    - cd ${WD} && fetch -q ${ARCHIVES_BASE}/src.txz
    - tar xf ${WD}/src.txz -C / && rm ${WD}/src.txz
    - fetch -o - https://github.com/freebsd/freebsd-src/pull/1859.patch |
      patch -d /usr/src -p1
    - make -C /usr/src/lib/libfetch all install
    - make -C /usr/src/usr.bin/fetch all install
  build_script:
    - make -j${CIRRUS_CPU}
    - make install
  manlint_script:
    - makewhatis /usr/share/man
    # XXX: too many xrefs to manpages that don't exist in previous releases
    - test $(freebsd-version) '!=' 15.0-ALPHA4 || make manlint
  test_libfetch_setup_script:
    - pkg install -y socat
  test_server_background_script:
    - libfetch/test-server.sh
  libfetch_test_script:
    - until [ -n "$(sockstat -l | awk '$2 == "socat" && $6 ~ /:8080$/')" ]; do sleep 1; done
    - /usr/libexec/flua libfetch/test.lua
