DIRS=	FLUA_SYS
FLUA_SYS=	${LIBDIR}/flua/sys

.include <bsd.dirs.mk>

SUBDIR=	\
	acl \
	capsicum \
	cpuset \
	event \
	extattr \
	linker \
	mac \
	module \
	socket \
	stat \
	sysctl \

.include <bsd.subdir.mk>
