/*
 * Copyright (c) 2026 Ryan Moeller
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

#include <signal.h>

#include <lua.h>

/* TODO: signal(3) and sigaction(2) and related bindings */

int
luaopen_signal(lua_State *L)
{
	lua_newtable(L);
#define DEFINE(ident) ({ \
	lua_pushinteger(L, ident); \
	lua_setfield(L, -2, #ident); \
})
	DEFINE(SIGHUP);
	DEFINE(SIGINT);
	DEFINE(SIGQUIT);
	DEFINE(SIGILL);
	DEFINE(SIGTRAP);
	DEFINE(SIGABRT);
	DEFINE(SIGIOT);
	DEFINE(SIGEMT);
	DEFINE(SIGFPE);
	DEFINE(SIGKILL);
	DEFINE(SIGBUS);
	DEFINE(SIGSEGV);
	DEFINE(SIGSYS);
	DEFINE(SIGPIPE);
	DEFINE(SIGALRM);
	DEFINE(SIGTERM);
	DEFINE(SIGURG);
	DEFINE(SIGSTOP);
	DEFINE(SIGTSTP);
	DEFINE(SIGCONT);
	DEFINE(SIGCHLD);
	DEFINE(SIGTTIN);
	DEFINE(SIGTTOU);
	DEFINE(SIGIO);
	DEFINE(SIGXCPU);
	DEFINE(SIGXFSZ);
	DEFINE(SIGVTALRM);
	DEFINE(SIGPROF);
	DEFINE(SIGWINCH);
	DEFINE(SIGINFO);
	DEFINE(SIGUSR1);
	DEFINE(SIGUSR2);
	DEFINE(SIGTHR);
	DEFINE(SIGLWP);
	DEFINE(SIGLIBRT);
	DEFINE(SIGRTMIN);
	DEFINE(SIGRTMAX);
	DEFINE(SIGEV_NONE);
	DEFINE(SIGEV_SIGNAL);
	DEFINE(SIGEV_THREAD);
	DEFINE(SIGEV_KEVENT);
	DEFINE(SIGEV_THREAD_ID);
	DEFINE(ILL_ILLOPC);
	DEFINE(ILL_ILLOPN);
	DEFINE(ILL_ILLADR);
	DEFINE(ILL_PRVOPC);
	DEFINE(ILL_PRVREG);
	DEFINE(ILL_COPROC);
	DEFINE(ILL_BADSTK);
	DEFINE(BUS_ADRALN);
	DEFINE(BUS_ADRERR);
	DEFINE(BUS_OBJERR);
	DEFINE(BUS_OOMERR);
	DEFINE(SEGV_MAPERR);
	DEFINE(SEGV_ACCERR);
	DEFINE(SEGV_PKUERR);
	DEFINE(FPE_INTOVF);
	DEFINE(FPE_INTDIV);
	DEFINE(FPE_FLTDIV);
	DEFINE(FPE_FLTOVF);
	DEFINE(FPE_FLTUND);
	DEFINE(FPE_FLTRES);
	DEFINE(FPE_FLTINV);
	DEFINE(FPE_FLTSUB);
	DEFINE(FPE_FLTIDO);
	DEFINE(TRAP_BRKPT);
	DEFINE(TRAP_TRACE);
	DEFINE(TRAP_DTRACE);
	DEFINE(TRAP_CAP);
	DEFINE(CLD_EXITED);
	DEFINE(CLD_KILLED);
	DEFINE(CLD_DUMPED);
	DEFINE(CLD_TRAPPED);
	DEFINE(CLD_STOPPED);
	DEFINE(CLD_CONTINUED);
	DEFINE(POLL_IN);
	DEFINE(POLL_OUT);
	DEFINE(POLL_MSG);
	DEFINE(POLL_ERR);
	DEFINE(POLL_PRI);
	DEFINE(POLL_HUP);
	DEFINE(SA_ONSTACK);
	DEFINE(SA_RESTART);
	DEFINE(SA_RESETHAND);
	DEFINE(SA_NODEFER);
	DEFINE(SA_NOCLDWAIT);
	DEFINE(SA_SIGINFO);
	DEFINE(NSIG);
	DEFINE(SI_NOINFO);
	DEFINE(SI_USER);
	DEFINE(SI_QUEUE);
	DEFINE(SI_TIMER);
	DEFINE(SI_ASYNCIO);
	DEFINE(SI_MESGQ);
	DEFINE(SI_KERNEL);
	DEFINE(SI_LWP);
	DEFINE(SI_UNDEFINED);
	DEFINE(SIG_BLOCK);
	DEFINE(SIG_UNBLOCK);
	DEFINE(SIG_SETMASK);
#undef DEFINE
#define DEFINE(ident) ({ \
	lua_pushinteger(L, (intptr_t)ident); \
	lua_setfield(L, -2, #ident); \
})
	DEFINE(BADSIG);
	DEFINE(SIG_DFL);
	DEFINE(SIG_IGN);
	DEFINE(SIG_ERR);
	DEFINE(SIG_HOLD);
#undef DEFINE
	return (1);
}
