nvpair = require('nvpair')
zfs = require('zfs')

hdl = zfs.init()
assert(hdl:iter_pools(function(pool)
	name = pool:get_name()
	state = pool:get_state()
	print('pool:', name, 'state:', state)
	pool:close()
end))
hdl:fini()
hdl = zfs.init()
assert(hdl:iter_root(function(ds)
	name = ds:get_name()
	print('root:', name)
	ds:close()
end))
hdl:fini()
