/*
 * Copyright (c) 2025 Ryan Moeller
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

#include <errno.h>
#include <stdio.h>
#include <unistd.h>

#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>

#include "../utils.h"

int luaopen_sysconf(lua_State *);

static int
l_sc_sysconf(lua_State *L)
{
	long value;
	int name;

	name = luaL_checkinteger(L, 1);

	errno = 0;
	if ((value = sysconf(name)) == -1) {
		if (errno == 0) {
			return (0);
		}
		return (fail(L, errno));
	}
	lua_pushinteger(L, value);
	return (1);
}

static const struct luaL_Reg l_sysconf_funcs[] = {
	{"sysconf", l_sc_sysconf},
	{NULL, NULL}
};

int
luaopen_sysconf(lua_State *L)
{
	luaL_newlib(L, l_sysconf_funcs);
#define SETCONST(ident) ({ \
	lua_pushinteger(L, _SC_ ## ident); \
	lua_setfield(L, -2, #ident); \
})
	SETCONST(ARG_MAX);
	SETCONST(CHILD_MAX);
	SETCONST(CLK_TCK);
	SETCONST(NGROUPS_MAX);
	SETCONST(OPEN_MAX);
	SETCONST(JOB_CONTROL);
	SETCONST(SAVED_IDS);
	SETCONST(VERSION);
	SETCONST(BC_BASE_MAX);
	SETCONST(BC_DIM_MAX);
	SETCONST(BC_SCALE_MAX);
	SETCONST(BC_STRING_MAX);
	SETCONST(COLL_WEIGHTS_MAX);
	SETCONST(EXPR_NEST_MAX);
	SETCONST(LINE_MAX);
	SETCONST(RE_DUP_MAX);
	SETCONST(2_VERSION);
	SETCONST(2_C_BIND);
	SETCONST(2_C_DEV);
	SETCONST(2_CHAR_TERM);
	SETCONST(2_FORT_DEV);
	SETCONST(2_FORT_RUN);
	SETCONST(2_LOCALEDEF);
	SETCONST(2_SW_DEV);
	SETCONST(2_UPE);
	SETCONST(STREAM_MAX);
	SETCONST(TZNAME_MAX);
	SETCONST(ASYNCHRONOUS_IO);
	SETCONST(MAPPED_FILES);
	SETCONST(MEMLOCK);
	SETCONST(MEMLOCK_RANGE);
	SETCONST(MEMORY_PROTECTION);
	SETCONST(MESSAGE_PASSING);
	SETCONST(PRIORITIZED_IO);
	SETCONST(PRIORITY_SCHEDULING);
	SETCONST(REALTIME_SIGNALS);
	SETCONST(SEMAPHORES);
	SETCONST(FSYNC);
	SETCONST(SHARED_MEMORY_OBJECTS);
	SETCONST(SYNCHRONIZED_IO);
	SETCONST(TIMERS);
	SETCONST(AIO_LISTIO_MAX);
	SETCONST(AIO_MAX);
	SETCONST(AIO_PRIO_DELTA_MAX);
	SETCONST(DELAYTIMER_MAX);
	SETCONST(MQ_OPEN_MAX);
	SETCONST(PAGESIZE);
	SETCONST(RTSIG_MAX);
	SETCONST(SEM_NSEMS_MAX);
	SETCONST(SEM_VALUE_MAX);
	SETCONST(SIGQUEUE_MAX);
	SETCONST(TIMER_MAX);
	SETCONST(2_PBS);
	SETCONST(2_PBS_ACCOUNTING);
	SETCONST(2_PBS_CHECKPOINT);
	SETCONST(2_PBS_LOCATE);
	SETCONST(2_PBS_MESSAGE);
	SETCONST(2_PBS_TRACK);
	SETCONST(ADVISORY_INFO);
	SETCONST(BARRIERS);
	SETCONST(CLOCK_SELECTION);
	SETCONST(CPUTIME);
	SETCONST(FILE_LOCKING);
	SETCONST(GETGR_R_SIZE_MAX);
	SETCONST(GETPW_R_SIZE_MAX);
	SETCONST(HOST_NAME_MAX);
	SETCONST(LOGIN_NAME_MAX);
	SETCONST(MONOTONIC_CLOCK);
	SETCONST(MQ_PRIO_MAX);
	SETCONST(READER_WRITER_LOCKS);
	SETCONST(REGEXP);
	SETCONST(SHELL);
	SETCONST(SPAWN);
	SETCONST(SPIN_LOCKS);
	SETCONST(SPORADIC_SERVER);
	SETCONST(THREAD_ATTR_STACKADDR);
	SETCONST(THREAD_ATTR_STACKSIZE);
	SETCONST(THREAD_CPUTIME);
	SETCONST(THREAD_DESTRUCTOR_ITERATIONS);
	SETCONST(THREAD_KEYS_MAX);
	SETCONST(THREAD_PRIO_INHERIT);
	SETCONST(THREAD_PRIO_PROTECT);
	SETCONST(THREAD_PRIORITY_SCHEDULING);
	SETCONST(THREAD_PROCESS_SHARED);
	SETCONST(THREAD_SAFE_FUNCTIONS);
	SETCONST(THREAD_SPORADIC_SERVER);
	SETCONST(THREAD_STACK_MIN);
	SETCONST(THREAD_THREADS_MAX);
	SETCONST(TIMEOUTS);
	SETCONST(THREADS);
	SETCONST(TRACE);
	SETCONST(TRACE_EVENT_FILTER);
	SETCONST(TRACE_INHERIT);
	SETCONST(TRACE_LOG);
	SETCONST(TTY_NAME_MAX);
	SETCONST(TYPED_MEMORY_OBJECTS);
	SETCONST(V6_ILP32_OFF32);
	SETCONST(V6_ILP32_OFFBIG);
	SETCONST(V6_LP64_OFF64);
	SETCONST(V6_LPBIG_OFFBIG);
	SETCONST(IPV6);
	SETCONST(RAW_SOCKETS);
	SETCONST(SYMLOOP_MAX);
	SETCONST(ATEXIT_MAX);
	SETCONST(IOV_MAX);
	SETCONST(PAGE_SIZE);
	SETCONST(XOPEN_CRYPT);
	SETCONST(XOPEN_ENH_I18N);
	SETCONST(XOPEN_LEGACY);
	SETCONST(XOPEN_REALTIME);
	SETCONST(XOPEN_REALTIME_THREADS);
	SETCONST(XOPEN_SHM);
	SETCONST(XOPEN_STREAMS);
	SETCONST(XOPEN_UNIX);
	SETCONST(XOPEN_VERSION);
	SETCONST(XOPEN_XCU_VERSION);
	SETCONST(NPROCESSORS_CONF);
	SETCONST(NPROCESSORS_ONLN);
	SETCONST(CPUSET_SIZE);
#ifdef _SC_UEXTERR_MAXLEN
	SETCONST(UEXTERR_MAXLEN);
#endif
#ifdef _SC_NSIG
	SETCONST(NSIG);
#endif
	SETCONST(PHYS_PAGES);
#undef SETCONST
	return (1);
}
